"""first migration

Revision ID: 16e0a72dbcad
Revises: 
Create Date: 2021-03-05 21:25:07.363401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e0a72dbcad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('chat_id', sa.String(length=255), nullable=False),
    sa.Column('chat_name', sa.String(length=255), nullable=True),
    sa.Column('chat_state', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(length=1024), nullable=True),
    sa.Column('message_id', sa.String(length=128), nullable=True),
    sa.Column('last_notify_id', sa.String(length=128), nullable=True),
    sa.Column('period_days', sa.Integer(), nullable=True),
    sa.Column('last_done_time', sa.DateTime(), nullable=True),
    sa.Column('done_mark_user_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_chat_id'), 'task', ['chat_id'], unique=False)
    op.create_index(op.f('ix_task_done_mark_user_id'), 'task', ['done_mark_user_id'], unique=False)
    op.create_index(op.f('ix_task_last_notify_id'), 'task', ['last_notify_id'], unique=False)
    op.create_index(op.f('ix_task_message_id'), 'task', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_message_id'), table_name='task')
    op.drop_index(op.f('ix_task_last_notify_id'), table_name='task')
    op.drop_index(op.f('ix_task_done_mark_user_id'), table_name='task')
    op.drop_index(op.f('ix_task_chat_id'), table_name='task')
    op.drop_table('task')
    op.drop_table('chat')
    # ### end Alembic commands ###
