"""ref chat to editing task

Revision ID: eeee92384a9f
Revises: 16e0a72dbcad
Create Date: 2021-03-05 23:39:56.266255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeee92384a9f'
down_revision = '16e0a72dbcad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('editing_task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_editing_task_id'), 'chat', ['editing_task_id'], unique=False)
    op.create_foreign_key(None, 'chat', 'task', ['editing_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_index(op.f('ix_chat_editing_task_id'), table_name='chat')
    op.drop_column('chat', 'editing_task_id')
    # ### end Alembic commands ###
