"""added fields

Revision ID: 493cc96ab738
Revises: fb541cb39ab9
Create Date: 2021-03-11 09:59:35.509671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493cc96ab738'
down_revision = 'fb541cb39ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('notify_next_date_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_chat_notify_next_date_time'), 'chat', ['notify_next_date_time'], unique=False)
    op.add_column('task', sa.Column('exact_in_time', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'exact_in_time')
    op.drop_index(op.f('ix_chat_notify_next_date_time'), table_name='chat')
    op.drop_column('chat', 'notify_next_date_time')
    # ### end Alembic commands ###
