"""added field task.notify_time

Revision ID: fb541cb39ab9
Revises: eeee92384a9f
Create Date: 2021-03-10 21:08:55.871972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb541cb39ab9'
down_revision = 'eeee92384a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('notify_time', sa.DateTime(),
                                    nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'notify_time')
    # ### end Alembic commands ###
